version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: trello
      POSTGRES_USER: trello
      POSTGRES_PASSWORD: trello
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
