version: '3'

services:
  postgres:
    image: postgres
    container_name: book-review-test-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: book-review
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: book
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
