name: "Run flow"

on:
  push:
    branches:
      - "main"
      - "develop"

jobs:
  telegram-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Push notify.
        if: ${{ github.event_name == 'push' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} just pushed ${{ github.ref }} into ${{ github.repository }} with comment "${{ github.event.head_commit.message }}"
            ${{ github.event.compare }}

      - name: PR notify
        if: ${{ github.event_name == 'pull_request' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} just opened PR in ${{ github.repository }} with comment "${{github.event.pull_request.title}}"
            ${{ github.event.pull_request.html_url }}

#  maven-build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Java JDK 8
#        uses: actions/setup-java@v2
#        with:
#          java-version: '8'
#          distribution: 'adopt'
#
#      - name: Maven build
#        run: mvn clean compile

#  docker-build:
#    runs-on: ubuntu-latest
##    needs:
##      - maven-build
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Java JDK 8
#        uses: actions/setup-java@v2
#        with:
#          java-version: '8'
#          distribution: 'adopt'
#
#      - name: Maven package
#        run: mvn clean package -DskipTests
#
#      - name: SetUp QEMU
#        uses: docker/setup-qemu-action@v1
#
#      - name: Set up Docker buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Run docker containers
#        run: docker-compose build
#
#  tests:
#    runs-on: ubuntu-latest
#    needs:
#      - docker-build
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: SetUp QEMU
#        uses: docker/setup-qemu-action@v1
#
#      - name: Set up Docker buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Run docker containers
#        run: docker-compose -f docker-compose.test.db.yml up -d
#
#      - name: Maven tests
#        run: mvn test
#
#      - name: Stop docker containers
#        run: docker-compose -f docker-compose.test.db.yml stop
#
#      - name: Remove docker containers
#        run: docker-compose -f docker-compose.test.db.yml rm -f

  deploy:
    runs-on: ubuntu-latest
    needs:
      - tests
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Maven package
        run: mvn clean package -DskipTests

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: "anvar00755@mail.ru"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mybook-anvar"
